name: mqtt_client
description: A server and browser based MQTT client for Dart supporting normal, secure sockets and websockets.
version: 6.0.0
homepage: https://github.com/shamblett/mqtt_client

environment:
 sdk: ">=2.0.0-dev  <3.0.0"

dependencies:
 typed_data: '^1.1.6'
 event_bus: '^1.1.0'
 path: '^1.6.4'
 crypto: '^2.1.3'
 meta: '^1.1.8'

dev_dependencies:
 test: '^1.11.0'
 mockito: '^4.1.1'
 pedantic: '^1.9.0'
 pana: '^0.13.4'
 build_runner: '^1.7.3'
 build_test: '^0.10.12'
 build_web_compilers: '^2.8.0'





